nama = input("siapa nama saya?")
umur = input("berapa umur saya?")
hobi = input("apa hobi kamu?")
warna = input("apa warna kesukaan saya?")
makanan = input("apa makanan kesukaan saya?")
minuman = input("apa minuman kesukaan saya?")
sekolah = input("nama sokolah saya?")
kelas = input("kelas berapa saya?")
kejurusan = input("apa jurusan saya?")
saudara = input("berapa saudara saya?")

print("nama sya",nama,"umur saya",umur,"hobi saya",hobi,"warna saya",warna,"makanan saya",makanan,"minuman saya",minuman,"sekolah saya",sekolah,"kelas saya",kelas,"kejurusan saya",kejurusan,"saudara saya",saudara)